### PR TITLE
Remove deprecated missing value functions

### PR DESCRIPTION
**Pull request by lokeshh**

### CODE REVIEW

**Comment by v0dro** [comment]
A new version of daru has been released. Make this build pass with it and I'll merge.

**Comment by lokeshh** [comment]
@v0dro I'm getting three failures. These aren't caused by missing values PR but some other change in Daru. I'm having a look. These are weird errors:

```ruby
NameError: uninitialized constant Daru::Vector::ERB
```

**Comment by lokeshh** [comment]
I've fixed the issues for now and the build should pass now. The fix is temporary although though. See https://github.com/SciRuby/statsample/pull/55/commits/d4180335ad7e5269a5a6b36ab508902fc4f0684c

**Comment by lokeshh** [comment]
There's one more error remaining to be solved:

```ruby
An error occurred while installing activesupport (5.0.0.1), and Bundler cannot continue
```

**Comment by lokeshh** [comment]
The problem is that activesupport requires Ruby version >= 2.2.2.

**Comment by v0dro** [comment]
Check it now. I've released a new daru version with the necessary `require` statements that wern't happening since we removed all dependencies.

**Comment by lokeshh** [comment]
Yep, working fine now.

**Pull request merged**
