### PR TITLE
fix [].mean method

### LINKED ISSUE #44: Array:mean method bug
Firstly the following seems to be a bug

```
require 'statsample'
[1, 2].mean => 1
```
This should be 1.5...

See https://github.com/SciRuby/statsample/blob/master/lib/statsample.rb#L62

i.e. That section should be 

```
def mean
  self.sum.to_f / size
end
```

### PR DESCRIPTION
**Pull request by IsmailM**
Fixes #44

### CODE REVIEW

**Comment by mikecmpbll** [comment]
this is really petty but I've always preferred `1.fdiv(2)` over `1.to_f/2` and it's faster too.

```ruby
require 'benchmark/ips'
Benchmark.ips do |x|
  x.report('fdiv') { 1.fdiv(2) }
  x.report('to_f') { 1.to_f/2 }
  x.compare!
end
Calculating -------------------------------------
                fdiv    65.294k i/100ms
                to_f    64.008k i/100ms
-------------------------------------------------
                fdiv      5.545M (± 7.3%) i/s -     27.554M
                to_f      4.186M (± 6.0%) i/s -     20.867M

Comparison:
                fdiv:  5545234.9 i/s
                to_f:  4186422.3 i/s - 1.32x slower
```

*shrugs* :neckbeard: :grin:

**Comment by IsmailM** [comment]
Thanks @mikecmpbll - I’ve never come across fdiv before…

Anyways. Done.

**Comment by IsmailM** [comment]
@mikecmpbll 

Using `fdiv` makes travis sad… Any idea why?

`to_f` = https://travis-ci.org/SciRuby/statsample/builds/86715122 (passing)
`fdiv` = https://travis-ci.org/SciRuby/statsample/builds/86722385 (failing)

Shall I change back to `to_f`

**Comment by mikecmpbll** [comment]
weird?? :/ didn't mean to cause an issue here. i can look into why this fails tomorrow, but up to you guys.

**Comment by IsmailM** [comment]
Thanks

Could just be a hiccup from Travis; Can someone (with the permissions) restart this [build](https://travis-ci.org/SciRuby/statsample/jobs/86722391) - perhaps it will ‘automagically’ fix things.

**Comment by IsmailM** [comment]
Okay, the build now passes...

**Comment by mikecmpbll** [comment]
:+1: :wink:

**Comment by v0dro** [comment]
Could you please rebase this feature into a single commit?

**Comment by IsmailM** [comment]
@v0dro, as requested, this has now been rebased into a single commit.

**Comment by agarie** [comment]
Thanks @IsmailM!

**Pull request merged**
