### PR TITLE
Auto-corrected some files

### PR DESCRIPTION
**Pull request by agarie**
Gigantic PR ahead. I'm using Rubocop's `--auto-correct` on the source to see how good it is and what we can gain by using it.

Let's see if Travis agrees that this is good progress. :-)

UPDATE: So dataset.rb didn't like Rubocop after all. I'll change some more files before merging this PR.

### CODE REVIEW

**Comment by mikecmpbll** [comment]
Would be good to see the whole source rubocopped, :+1:

**Comment by mohawkjohn** [comment]
Nifty.

**Comment by v0dro** [comment]
@agarie let's close this and rubocop the new code?

**Comment by agarie** [comment]
@v0dro sure. (I forgot about this PR -_-)

**Pull request closed without merging**
