### PR TITLE
Add an example for chi-square homogeneity test

### PR DESCRIPTION
**Pull request by onli**
I was yesterday struggling to do the chi-square test as a plain homogeneity test. The "create a matrix" approach went over my head. I hope that this additional example might be useful.

### CODE REVIEW

**Comment by agarie** [comment]
Hey @onli, thanks for reopening this PR. However, there is a test failure in Travis (but only in 1.9.3:

[travis-ci.org/SciRuby/statsample/jobs/54844362](https://travis-ci.org/SciRuby/statsample/jobs/54844362)

I'm still in the process of moving issues and asking other PR authors to reopen them in the SciRuby org page. As soon as I have some time, I'll fix that before merging, ok? :P

If you have any idea why that failure is happening, please help! :)

**Comment by onli** [comment]
> As soon as I have some time, I'll fix that before merging, ok? :P

Sure!

However, I don't think that travis error is caused by my code, since the failed assertion stems from another file. And this example code is probably not too important, as it is just an example, not the actual code of the project. 

I have no idea why it is happening though, sorry.

**Comment by agarie** [comment]
That's fine. I should be able to work on this in a couple of days.

**Comment by onli** [comment]
@agarie I think that got forgotten. Still a chance to merge that?

**Comment by v0dro** [comment]
Merging.

**Comment by onli** [comment]
Thanks! Yes, seems that travis just died there without actually testing anything.

**Pull request merged**
